services:
  node:
    env_file: 
      - .env
    build: .
    image: nmm_bot
    # container_name: nmm_django
    ports:
      - "8100:3000"
    networks:
      - jungle_network

networks:
  jungle_network:
    external: true
    driver: bridge